name: travelapp
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.1
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.13
  http: ^0.13.4
  flutter_svg: ^1.0.3
  flutter_markdown: ^0.6.10

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
